app/routes.py
import requests
import pyotp

from flask import flash, redirect, render_template, request, session, abort, Blueprint, url_for
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
from app.models import  db, Users, Birthdays, AuditLogs
from app.helpers import apology, log, calculate_age, date_convert, password_set, generate_otp_code, send_otp_email, verify_otp_code, generate_potp_secret_key, email_confirmed, verification_email

from sqlalchemy.sql import func


main = Blueprint('main', __name__)
POTP_SECRET_KEY = pyotp.random_base32()

@main.route("/")
def index():
    """Homepage"""
    # Forget any user_id
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    return render_template("index.html")


@main.route("/register", methods=["GET", "POST"])
def register():
    """Register user"""
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")
        phone = request.form.get("phone")
        dob = request.form.get("dob")
        name = request.form.get("name")
        password = request.form.get("password")
        confirmation = request.form.get("confirmation")
        hash = generate_password_hash(password, method='pbkdf2:sha256:600000', salt_length=16)
            
        if not username or not password or not email or not phone or not name:
            return apology("All fields are required!! ", 400)
        
        if password != confirmation:
            return apology("Password Mismatch!! ", 400)
        
        try:
            user = Users(name=name, username=username, hash=hash, dob=dob, email=email, phone=phone, password_set=True, totp_secret = generate_potp_secret_key())
            db.session.add(user)
            db.session.commit()

            user = Users.query.filter_by(username=username).first()
            if not user or not check_password_hash(user.hash,password):
                return apology("Invalid Username or Password!! ", 404)

            login_user(user)
            log("register")

        except ValueError:
            return apology("Username already exists!! ", 403)
        
        verification_email(current_user)
        return redirect(url_for("main.otp_verification"))
    
    else:
        return render_template("register.html")
    

@main.route("/otp_verification", methods=["GET", "POST"])
@login_required
@password_set
def otp_verification():
    if request.method == "POST":
        if 'resend_otp' in request.form:
            time_last_otp_sent = None
            if current_user.last_otp_sent: 
                time_last_otp_sent = (datetime.now() - current_user.last_otp_sent).total_seconds()  
                if time_last_otp_sent and time_last_otp_sent < 60:
                    flash(f"Resend otp in {60 - int(time_last_otp_sent)} seconds!! ")
                else:
                    verification_email(current_user)
                return redirect(url_for("main.otp_verification"))
            else:
                verification_email(current_user)
            return redirect(url_for("main.otp_verification"))
        else:
            otp = request.form.get("otp")
            if not otp:
                flash("Please Enter OTP! ")
                return redirect(url_for("main.otp_verification"))
            
            if verify_otp_code(current_user.totp_secret, otp):
                current_user.confirmed = True
                current_user.confirmed_on = datetime.now()
                db.session.commit()
                flash("OTP verification successful! ")
                log("otp_verified")
                return redirect(url_for("main.home"))
            else: 
                flash("Invalid or expired OTP!! ")
                log("OTP_verification_failed!! ")
                return redirect(url_for("main.otp_verification"))
            
    time_last_otp_sent = None
    if current_user.last_otp_sent: 
        time_last_otp_sent = (datetime.now() - current_user.last_otp_sent).total_seconds()
        countdown = max(0, int(60 - time_last_otp_sent)) if time_last_otp_sent else 60

    return render_template("otp_verification.html", user=current_user, countdown=countdown)


@main.route("/add_password", methods=["GET", "POST"])
def add_password():
    """Register user"""
    if current_user.password_set:
        flash("Already added Password")
        return redirect(url_for("main.index"))

    if request.method == "POST":
        password = request.form.get("password")
        confirmation = request.form.get("confirmation")
        
        if not password or not confirmation:
            return apology("All fields are required!!", 400)
        
        if password != confirmation:
            return apology("Password Mismatch", 400)
        
        current_user.hash = generate_password_hash(password, method='pbkdf2:sha256:600000', salt_length=16)
        current_user.password_set = True
        db.session.commit()

        log("google_register")

        if not current_user.confirmed:
            verification_email(current_user)
            return redirect(url_for("main.otp_verification"))
    
    return render_template("add_password.html", user=current_user)


@main.route("/login", methods=["GET", "POST"])
def login():
    """Log user in"""
    # User reached route via POST (as by submitting a form via POST)
    if request.method == "POST":
        # Ensure username was submitted
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            return apology("Must provide Username or Password", 403)

        # Query database for username
        user = Users.query.filter_by(username=username).first()

        # Ensure username exists and password is correct
        if not user or not check_password_hash(user.hash, password):
            return apology("invalid username and/or password", 403)

        login_user(user)
        log("log_in")
        return redirect(url_for("main.home"))

    # User reached route via GET (as by clicking a link or via redirect)
    return render_template("login.html")


@main.route("/signin-google")
def googleCallback():
    from app import oauth_client
    # fetch access token and id token using authorization code
    try:
        token = oauth_client.myApp.authorize_access_token()

        personDataUrl = "https://people.googleapis.com/v1/people/me?personFields=genders,birthdays"

        headers = {'Authorization': f'Bearer {token["access_token"]}'}
        response = requests.get(personDataUrl, headers=headers)
        person_info = response.json()

        email = token["userinfo"]["email"]
        name = token["userinfo"]["name"]
        google_id = token["userinfo"]["sub"]
        
        birthday = None
        if "birthdays" in person_info and len(person_info["birthdays"]) > 1:
            date_info = person_info["birthdays"][1].get("date", {})
            day = date_info.get("day")
            month = date_info.get("month")
            year = date_info.get("year")
            birthday = f"{year}-{month:02d}-{day:02d}" if year else f"{month:02d}-{day:02d}"

        user = Users.query.filter_by(email=email).first()
        if not user:
            user = Users(name=name, username=name, dob=birthday, email=email, google_id=google_id, totp_secret=generate_potp_secret_key(), last_otp_sent=datetime.now())
            db.session.add(user)
            db.session.commit()

        login_user(user)

        if not user.password_set:
            return redirect(url_for("main.add_password"))
        
        if not user.confirmed:
            verification_email(current_user)
            return redirect(url_for("main.otp_verification"))
                
        log(f"google_login_{name}")
        return redirect(url_for("main.home"))

    except ValueError:
        return apology("Unauthorized login", 403)

    

@main.route("/google-login")
def googleLogin():
    from app import oauth_client
    if current_user.is_authenticated:
        abort(404)
    return oauth_client.myApp.authorize_redirect(redirect_uri=url_for("main.googleCallback", _external=True))


@main.route("/home")
@login_required
@password_set
@email_confirmed
def home():
    '''Show friends whose birthday is that day'''
    user_id = current_user.id
   
    birthdays = Birthdays.query.filter(func.strftime('%d-%m',Birthdays.birthdates)==func.strftime('%d-%m', func.now()), Birthdays.user_id==user_id).all()

    for friend in birthdays:
        friend.age = calculate_age(friend.birthdates)
    
    return render_template("home.html", birthdays=birthdays)


@main.route("/birthdays")
@login_required
@password_set
@email_confirmed
def birthdays():
    '''list all friends and their birthdays'''
    birthdays = Birthdays.query.filter_by(user_id=current_user.id).all()

    for friend in birthdays:
        friend.age = calculate_age(friend.birthdates)
    
    return render_template("birthdays.html", birthdays=birthdays)


@main.route("/add_birthday", methods=["GET", "POST"])
@login_required
@password_set
@email_confirmed
def add_birthday():
    '''add Friend's birthday'''
    if request.method == "POST":
        email = request.form.get("email")
        phone = request.form.get("phone")
        birthdate = date_convert(request.form.get("birthdate"))
        name = request.form.get("name")
        age = calculate_age(birthdate)

        if not name or not birthdate or not phone or not email:
            flash("All fields are required")
    
        birthday = Birthdays(user_id=current_user.id, name=name, birthdates=birthdate, phone=phone, email=email, age=age)
        db.session.add(birthday)
        db.session.commit()

        log(f"added_{name}")
        flash(f"{name} added successfully")
        return redirect("/birthdays")
    

app/templates/Add_password.html
{% extends "layout.html" %}

{% block title %}
    Password for Auto logins
{% endblock %}

{% block main %}
<div class="d-flex justify-content-center align-items-left vh-90">
    <form action="/add_password" method="post" class="form-control p-4" style="max-width: 500px;">
        <h2 class="h2 rounded-pill mt-0 pt-0 text-bg-dark">Add Password</h2>
        <div class="mb-3 row text-center">
            <label for="password" class="col-sm-4 col-form-label">Password</label>
            <div class="col-sm-8">
                <input class="form-control mx-auto w-auto" name="password" placeholder="Password" type="password" required>
            </div>
        </div>
        <div class="mb-3 row text-center">
            <label for="confirm_password" class="col-sm-4 col-form-label">Confirm password</label>
            <div class="col-sm-8">
                <input class="form-control mx-auto w-auto" name="confirmation" placeholder="Confirm password" type="password" required>
            </div>
        </div>
        <div class="mb-3 row text-center">
            <button class="btn btn-success" type="submit">Proceed</button>
        </div>
    </form>
</div>

{% endblock %}

app/templates/add.html
{% extends "layout.html" %}

{% block title %}
    Add Friends Birthdays
{% endblock %}

{% block main %}
<div class="d-flex justify-content-center align-items-left vh-90">
    <form action="/add_birthday" method="post" class="form-control p-4" style="max-width: 500px;">
        <h2 class="h2 rounded-pill mt-0 pt-0 text-bg-dark">Add new Friend</h2>
        <div class="mb-3 row" >
            <label for="name" class="col-sm-4 col-form-label">Name</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="name" placeholder="Name" type="text" required> 
            </div>
        </div>
        <div class="mb-3 row">
            <label for="dob" class="col-sm-4 col-form-label">Birth Date</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="birthdate" placeholder="Date of Birth" type="date" required>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="phone" class="col-sm-4 col-form-label">Phone</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="phone" placeholder="Phone Number" type="text" required>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="email" class="col-sm-4 col-form-label">Email</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="email" placeholder="Email" type="email" required>
            </div>
        </div>
        <div class="mb-3 row">
            <button class="btn btn-primary" type="submit">Add Friend</button>
        </div>
    </form>
</div>
    
<script>
    flatpickr("input[name='birthdate']", {
        dateFormat: "Y-m-d",  
        maxDate: "today", 
    });
</script>
    
{% endblock %}

app/templates/apology.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <!-- https://memegen.link/ -->
    <!-- https://knowyourmeme.com/memes/grumpy-cat -->
    <img alt="{{ top }}" class="border img-fluid" src="https://api.memegen.link/images/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?background=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
{% endblock %}

app/templates/edit.html
{% extends "layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block main %}
<div class="d-flex justify-content-center align-items-left vh-90">
    <form action="/add_birthday" method="post" class="form-control p-4"  style="max-width: 500px;">
        <h2 class="h2 rounded-pill mt-0 pt-0 text-bg-dark">Edit Birthday</h2>
        <div class="mb-3 row" >
            <label for="name" class="col-sm-4 col-form-label">Name</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="name" placeholder="Name" type="text" required> 
            </div>
        </div>
        <div class="mb-3 row">
            <label for="dob" class="col-sm-4 col-form-label">Birth Date</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="birthdate" placeholder="Date of Birth" type="date" required>
            </div>
        </div>
        <div class="mb-3 row">
            <label for="phone" class="col-sm-4 col-form-label">Phone</label>
            <div class="col-sm-8">
                <input autocomplete="off" autofocus class="form-control mx-auto w-auto" name="phone" placeholder="Phone Number" type="text" required>
            </div>
        </div>
        <div class="mb-3 row">
            <button class="btn btn-primary" type="submit">Save Changes</button>
        </div>
    </form>
</div>

<script>
    flatpickr("input[name='birthdate']", {
        dateFormat: "Y-m-d",  
        maxDate: "today", 
    });
</script>
    
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <link href="/static/favicon.ico" rel="icon">
    <link href="/static/styles.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
        font-family: 'Inter', sans-serif;
        color: #212529;
        overflow-y: auto;
        }
        body.logged-in {
        background-image: url('/static/bd.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        }
        .navbar-custom {
        background-color: rgba(255, 255, 255, 0.95);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);
        }
        .navbar-brand-custom {
        font-size: 1.5rem;
        font-weight: bold;
        }
        .main-content {
        padding: 2rem;
        background-color: rgba(255, 255, 255, 0.9);
        border-radius: 0.5rem;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);
        margin-top: 1rem;
        }
        .footer-custom {
        background-color: #f8f9fa;
        padding: 1rem 0;
        margin-top: 2rem;
        }
        .nav-link-custom {
        font-weight: 500;
        color: #1a237e;
        transition: color 0.3s ease-in-out;
        }
        .nav-link-custom:hover {
        color: #0d47a1;
        }
        .text-navy {
        color: #1a237e !important;
        }
    </style>
    <title>Celebrate: {% block title %}{% endblock %}</title>
</head>
<body class="{% if current_user.confirmed %}logged-in{% endif %}">
    <nav class="navbar navbar-expand-md navbar-light navbar-custom">
        <div class="container-fluid">
            <a class="navbar-brand navbar-brand-custom" href="/">
                <span class="text-primary">🎂📔Birthday</span>
                <span class="text-danger">Diaries</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if current_user.confirmed %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle nav-link-custom" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">🎂 Birthdays</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/add_birthday">🎁 Add Birthday</a></li>
                            <li><a class="dropdown-item" href="/birthdays">🎊 View Birthdays</a></li>
                            <li><hr class="dropdown-divider"></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle nav-link-custom" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">⚙️ Preferences</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/profile">👤 Profile</a></li>
                            <li><a class="dropdown-item" href="/update_profile/{{ current_user.id }}">⌮ Profile Update</a></li>
                            <li><a class="dropdown-item" href="/password_reset">🔐 Reset Password</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="/logout">🛑 Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-custom" href="/login">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-custom" href="/register">Create Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-custom" href="{{ url_for('main.googleLogin') }}">
                            <img src="static/logo.jpg" alt="Google logo" style="width:20px; margin-right:10px;"> Sign in with Google
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% if current_user.confirmed %}
                <form class="d-flex" role="search" action="/search" method="post">
                    <input class="form-control me-2" name="name" type="search" placeholder="Friend's Name" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>

    {% if get_flashed_messages() %}
    <div class="alert alert-success text-center alert-custom" role="alert">
        {{ get_flashed_messages() | join(" ") }}
    </div>
    {% endif %}

    <main class="container main-content">
        {% block main %}{% endblock %}
    </main>

    <footer class="footer-custom text-center">
        <form action="https://validator.w3.org/check" enctype="multipart/form-data" method="post" target="_blank">
            <input name="doctype" type="hidden" value="HTML5">
            <input name="fragment" type="hidden">
            <input alt="Validate" src="/static/I_heart_validator.png" type="image">
        </form>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
            const html = '<!DOCTYPE ' +
            document.doctype.name +
            (document.doctype.publicId ? ' PUBLIC "' + document.doctype.publicId + '"': '') +
            (!document.doctype.publicId && document.doctype.systemId ? ' SYSTEM': '') +
            (document.doctype.systemId ? ' "' + document.doctype.systemId + '"': '') +
            '>\n' + document.documentElement.outerHTML;
            document.querySelector('form[action="https://validator.w3.org/check"] > input[name="fragment"]').value = html;
            });
        </script>
    </footer>
</body>
</html>

app/templates/new.html
<a href="#" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>


<script>
    function onSignIn(googleUser) {
        var id_token = googleUser.getAuthResponse().id_token;

        fetch('/google_login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ id_token: id_token })
        })
        .then(response => response.json())
        .then(data => {
            if (data.message) {
                alert(data.message);
                window.location.href = '/';
            } else {
                alert(data.error);
            }
        })
        .catch(error => console.error('Error:', error));
    }
</script>

app/templates/original_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <link href="/static/favicon.ico" rel="icon">
    <link href="/static/styles.css" rel="stylesheet">
    <title>Celebrate: {% block title %}{% endblock %}</title>
</head>
<body>
    {% if current_user.confirmed %}
    <nav class="navbar navbar-expand-md navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand badge" href="/"><span class="text-primary">🎂📔Birthday</span><span class="text-danger">Diaries</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"><span class="badge bg-dark">🏠Home</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><span class="badge bg-dark">🎂Birthdays</span></a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/add_birthday">🎁Add Birthday</a></li>
                            <li><a class="dropdown-item" href="/birthdays">🎊View Birthdays</a></li>
                            <li><hr class="dropdown-divider"></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><span class="badge bg-dark">⚙️Preferences</span></a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/profile">👤 Profile</a></li>
                            <li><a class="dropdown-item" href="/update_profile/{{ current_user.id }}">⌮Profile update</a></li>
                            <li><a class="dropdown-item" href="/password_reset">🔐Reset Password</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="/logout">🛑Logout</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="/search" method="post">
                    <input class="form-control me-2" name="name" type="search" placeholder="Friend's Name" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <a class="nav-link active" aria-current="page" href="/logout"><span class="badge bg-danger">🛑Logout</span></a>
            </div>
        </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-md navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><span class="text-primary">🎂📔Birthday</span><span class="text-danger">Diaries</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="/login"><span class="badge bg-success">Log in</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/register"><span class="badge bg-info">Create Account</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('main.googleLogin')}}"><img src="static/logo.jpg" alt="Google logo" style="width:20px; margin-right:10px;">Sign in with Google</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endif %}
    
    {% if get_flashed_messages() %}
    <div class="alert alert-success text-center" role="alert">
        {{ get_flashed_messages() | join(" ") }}
    </div>
    {% endif %}
    
    <main class="container py-5">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8">
                {% block main %}{% endblock %}
            </div>
        </div>
    </main>
    
    <footer class="text-center mt-5">
        <form action="https://validator.w3.org/check" enctype="multipart/form-data" method="post" target="_blank">
            <input name="doctype" type="hidden" value="HTML5">
            <input name="fragment" type="hidden">
            <input alt="Validate" src="/static/I_heart_validator.png" type="image">
        </form>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const html = '<!DOCTYPE ' +
                document.doctype.name +
                (document.doctype.publicId ? ' PUBLIC "' + document.doctype.publicId + '"' : '') +
                (!document.doctype.publicId && document.doctype.systemId ? ' SYSTEM' : '') +
                (document.doctype.systemId ? ' "' + document.doctype.systemId + '"' : '') +
                '>\n' + document.documentElement.outerHTML;
                document.querySelector('form[action="https://validator.w3.org/check"] > input[name="fragment"]').value = html;
            });
        </script>
    </footer>
</body>
</html>

app/templates/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block main %}
<div class="row align-items-center mb-5"> 
    <div class="col-md-7">
    <h3 class="display-3 fw-bold">
          <span class="text-primary">🎂Birthday</span><br><span class="text-danger"> 📔Diaries</span>
      </h3>
    </div>
    <div class="col-md-5">
    <div class="card p-4 shadow-sm">
    <form action="/register" method="post" class="p-4 mx-auto" style="max-width: 400px;">
    <div class="mb-3">
        <input autocomplete="off" class="form-control" name="name" placeholder="Name" type="text" required>
    </div>
    <div class="mb-3">
        <input autocomplete="off" class="form-control" name="username" placeholder="Username" type="text" required>
    </div>
    <div class="mb-3">
        <input autocomplete="off" class="form-control" name="dob" placeholder="Date of Birth" type="date" required>
    </div>
    <div class="mb-3">
        <input autocomplete="off" class="form-control" name="email" placeholder="Email" type="email" required>
    </div>
    <div class="mb-3">
        <input autocomplete="off" class="form-control" name="phone" placeholder="Phone number" type="text" required>
    </div>
    <div class="mb-3">
        <input class="form-control" name="password" placeholder="Password" type="password" required>
    </div>
    <div class="mb-3">
        <input class="form-control" name="confirmation" placeholder="Confirm Password" type="password" required>
    </div>
    <div class="d-grid mb-3">
        <button class="btn btn-success" type="submit">Register</button>
    </div>
    <div class="d-grid">
        <a class="btn btn-primary text-white" href="{{ url_for('main.googleLogin') }}">
            <img src="/static/logo.jpg" alt="Google logo" style="width:20px; margin-right:10px;"> Sign in with Google
        </a>
    </div>
</form>
</div>
</div>
</div>

<script>
        flatpickr("input[name='dob']", {
            dateFormat: "Y-m-d",  
            maxDate: "today", 
        });
</script>
{% endblock %}